language: php

php:
  - 5.6

env:
  - DB=mysql

before_script:
  - composer self-update --no-interaction
  - composer install --dev --prefer-source --no-interaction

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: vendor/bin/phpunit

